/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmEvPoslPart.java
 *
 * Created on 11.03.2009., 17:28:23
 */
package gui;

import java.util.Collection;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.jdesktop.beansbinding.AbstractBindingListener;
import org.jdesktop.beansbinding.PropertyStateEvent;

/**
 *
 * @author sheky
 */
public class frmEvPoslPart extends javax.swing.JPanel {
    //--Report

    public String reportPartner = "report/PopisPart_svi.jasper"; //.jrxml";
    public String reportKupci = "report/PopisPart_kupci.jasper"; //.jrxml";
    public String reportDobavljaci = "report/PopisPart_dobav.jasper"; //.jrxml";

    //--
    public int querVar = 2;
    public Integer vrstaPPVar = -1;
    public int varKupac = 0;
    public int varDobavljac = 1;
    private boolean isNewPart = false;
    private static int idVrPart = 0;
    public static JPanel newPanel = null;

    /** Creates new form frmEvPoslPart */
    public frmEvPoslPart() {
        initComponents();

        btnAcceptPart.setEnabled(false);
        btnAbort.setEnabled(false);
        btnDelPart.setEnabled(false);
        txtTipPart.setVisible(false);

        tblPartneri.getSelectionModel().addListSelectionListener(
                new ListSelectionListener() {

                    public void valueChanged(ListSelectionEvent e) {
                        btnDelPart.setEnabled(true);
                        if (!entityManager.getTransaction().isActive()) {
                            entityManager.getTransaction().begin();
                        }
                    }
                });


        bindingGroup.addBindingListener(new AbstractBindingListener() {

            @Override
            public void targetChanged(org.jdesktop.beansbinding.Binding binding, PropertyStateEvent event) {
                setSaveBtn(true);
            }
        });



    //entityManager.getTransaction().begin();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        nPrikazaBtnGrp = new javax.swing.ButtonGroup();
        tipPoslPartBtnGrp = new javax.swing.ButtonGroup();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("purgarPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT p FROM Partner p");
        listQuery = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPartneri = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        rbPartSvi = new javax.swing.JRadioButton();
        rbPartKupci = new javax.swing.JRadioButton();
        rbPartDobav = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbKupci = new javax.swing.JRadioButton();
        rbDobav = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMjesto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPostBr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAdresa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMatBr = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtBankRac = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnNewPartner = new javax.swing.JButton();
        btnAcceptPart = new javax.swing.JButton();
        btnAbort = new javax.swing.JButton();
        btnDelPart = new javax.swing.JButton();
        btnPrintPart = new javax.swing.JButton();
        txtTipPart = new javax.swing.JTextField();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listQuery, tblPartneri);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${maticniBr}"));
        columnBinding.setColumnName("Maticni Br");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ime}"));
        columnBinding.setColumnName("Ime");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${prezime}"));
        columnBinding.setColumnName("Prezime");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${mjesto}"));
        columnBinding.setColumnName("Mjesto");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${adresa}"));
        columnBinding.setColumnName("Adresa");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${naziv}"));
        columnBinding.setColumnName("Naziv");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tblPartneri);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Način prikaza"));

        nPrikazaBtnGrp.add(rbPartSvi);
        rbPartSvi.setSelected(true);
        rbPartSvi.setText("Svi partneri");
        rbPartSvi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbPartSviItemStateChanged(evt);
            }
        });
        rbPartSvi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPartSviActionPerformed(evt);
            }
        });

        nPrikazaBtnGrp.add(rbPartKupci);
        rbPartKupci.setText("Kupci");
        rbPartKupci.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbPartKupciItemStateChanged(evt);
            }
        });

        nPrikazaBtnGrp.add(rbPartDobav);
        rbPartDobav.setText("Dobavljači");
        rbPartDobav.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbPartDobavItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbPartSvi)
                    .addComponent(rbPartDobav)
                    .addComponent(rbPartKupci))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(rbPartSvi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbPartDobav)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbPartKupci))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Poslovni partner"));
        jPanel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel3FocusGained(evt);
            }
        });

        jLabel1.setText("Tip poslovnog partnera:");

        tipPoslPartBtnGrp.add(rbKupci);
        rbKupci.setText("Kupac");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), rbKupci, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        rbKupci.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbKupciItemStateChanged(evt);
            }
        });

        tipPoslPartBtnGrp.add(rbDobav);
        rbDobav.setText("Dobavljač");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), rbDobav, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        rbDobav.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbDobavItemStateChanged(evt);
            }
        });

        jLabel2.setText("Naziv:");

        jLabel3.setText("Ime:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.naziv}"), txtNaziv, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtNaziv, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.ime}"), txtIme, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtIme, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jLabel4.setText("Prezime:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.prezime}"), txtPrezime, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtPrezime, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jLabel5.setText("Telefon:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.telefon}"), txtTel, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtTel, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jLabel6.setText("Mjesto:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.mjesto}"), txtMjesto, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtMjesto, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jLabel7.setText("Poštanski broj:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.postBroj}"), txtPostBr, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtPostBr, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jLabel8.setText("Adresa:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.adresa}"), txtAdresa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtAdresa, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jLabel9.setText("Maticni broj:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.maticniBr}"), txtMatBr, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtMatBr, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jLabel10.setText("Bankovni račun:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.ziroRac}"), txtBankRac, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtBankRac, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jPanel4.setLayout(new java.awt.GridLayout(5, 0, 0, 4));

        btnNewPartner.setText("Dodaj novog partnera");
        btnNewPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPartnerActionPerformed(evt);
            }
        });
        jPanel4.add(btnNewPartner);

        btnAcceptPart.setText("Prihvati promejnu");
        btnAcceptPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptPartActionPerformed(evt);
            }
        });
        jPanel4.add(btnAcceptPart);

        btnAbort.setText("Odustani");
        btnAbort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbortActionPerformed(evt);
            }
        });
        jPanel4.add(btnAbort);

        btnDelPart.setText("Obriši");
        btnDelPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelPartActionPerformed(evt);
            }
        });
        jPanel4.add(btnDelPart);

        btnPrintPart.setText("Ispiši partnere");
        btnPrintPart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintPartActionPerformed(evt);
            }
        });
        jPanel4.add(btnPrintPart);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblPartneri, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idVrsta}"), txtTipPart, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceUnreadableValue(null);
        bindingGroup.addBinding(binding);

        txtTipPart.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTipPartCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAdresa))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbKupci)
                        .addGap(18, 18, 18)
                        .addComponent(rbDobav)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTipPart, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTel, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(txtMjesto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPostBr))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtMatBr, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrezime))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBankRac)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(rbKupci)
                            .addComponent(rbDobav)
                            .addComponent(txtTipPart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtMatBr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMjesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtPostBr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtBankRac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void rbPartSviItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbPartSviItemStateChanged
        querOdabir(2);
    }//GEN-LAST:event_rbPartSviItemStateChanged

    private void rbPartDobavItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbPartDobavItemStateChanged
        querOdabir(1);
    }//GEN-LAST:event_rbPartDobavItemStateChanged

    private void rbPartKupciItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbPartKupciItemStateChanged
        querOdabir(0);
    }//GEN-LAST:event_rbPartKupciItemStateChanged

    private void txtTipPartCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTipPartCaretUpdate
        getSelected_TipPart();
    }//GEN-LAST:event_txtTipPartCaretUpdate

    private void rbKupciItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbKupciItemStateChanged
        if ((varKupac != vrstaPPVar) && rbKupci.isSelected()) {
            System.out.println("kupac - vrsta:" + vrstaPPVar + "    sel:" + varKupac);
            setSelected_TipPart(varKupac);
        }

    }//GEN-LAST:event_rbKupciItemStateChanged

    private void rbDobavItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbDobavItemStateChanged
        if ((varDobavljac != vrstaPPVar) && rbDobav.isSelected()) {
            System.out.println("dobavljac - vrsta:" + vrstaPPVar + "    sel:" + varDobavljac);
            setSelected_TipPart(varDobavljac);
        }


    }//GEN-LAST:event_rbDobavItemStateChanged

    private void btnNewPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPartnerActionPerformed
        addNewPart();
    }//GEN-LAST:event_btnNewPartnerActionPerformed

    private void btnAcceptPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptPartActionPerformed
        accpetPart();
    }//GEN-LAST:event_btnAcceptPartActionPerformed

    private void btnAbortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbortActionPerformed
        abortPart();
    }//GEN-LAST:event_btnAbortActionPerformed

    private void btnDelPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelPartActionPerformed
        String[] button = {"Da", "Ne"};
        String poruka = "Dali sigurno želite obrisati podatke o poslovnom partneru?";
        String naslov = "Poslovni partner";
        int resp = JOptionPane.showOptionDialog(null, poruka, naslov, 0, JOptionPane.QUESTION_MESSAGE, null, button, 0);
        if (resp == 0) {
            delPart();

            String[] btn = {"Uredu"};
            JOptionPane.showOptionDialog(null, "Podaci o poslovnom partneru su obrisani!", "Poslovni partner", 0, JOptionPane.INFORMATION_MESSAGE, null, btn, 0);
        }
    }//GEN-LAST:event_btnDelPartActionPerformed

    private void btnPrintPartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintPartActionPerformed
        showReport();
    }//GEN-LAST:event_btnPrintPartActionPerformed

    private void rbPartSviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPartSviActionPerformed
    }//GEN-LAST:event_rbPartSviActionPerformed

    private void jPanel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel3FocusGained
        System.out.println("frmEvPoslPart shown...");
        MainWindow.openJPanel(this, false);
    }//GEN-LAST:event_jPanel3FocusGained

    public void showReport() {
        String reportPath = null;
        if (rbPartSvi.isSelected()) {
            reportPath = reportPartner;
        }
        if (rbPartDobav.isSelected()) {
            reportPath = reportDobavljaci;
        }
        if (rbPartKupci.isSelected()) {
            reportPath = reportKupci;
        }

        frmPdfRead newReader = new frmPdfRead(reportPath);
        newReader.setParentJPanel(this);
        MainWindow.openJPanel(newReader, false);
        System.out.println(entityManager.getDelegate().toString());
    }

    public void getSelected_TipPart() {
        if ((!txtTipPart.getText().isEmpty())) {
            Integer nv = Integer.parseInt(txtTipPart.getText());
            if (vrstaPPVar != nv) {
                System.out.println("txtTipPart:" + txtTipPart.getText());

                if (Integer.parseInt(txtTipPart.getText()) == varKupac) {
                    vrstaPPVar = varKupac;
                    rbKupci.setSelected(true);
                }
                if (Integer.parseInt(txtTipPart.getText()) == varDobavljac) {
                    vrstaPPVar = varDobavljac;
                    rbDobav.setSelected(true);
                }
            }
        }
    }

    public void setSelected_TipPart(Integer var) {
        if (rbKupci.isSelected()) {
            txtTipPart.setText(var.toString());

        }
        if (rbDobav.isSelected()) {
            txtTipPart.setText(var.toString());
        }

        vrstaPPVar = var;
    }

    public void querOdabir(int var) {
        if (querVar != var) {
            querVar = var;
        } else {
            return;
        }

        String strQuery = null;
        if (var == varKupac) { //kupac
            strQuery = "SELECT p FROM Partner p WHERE p.idVrsta = " + var;
        } else if (var == varDobavljac) { //dobavljac
            strQuery = "SELECT p FROM Partner p WHERE p.idVrsta = " + var;
        } else if (var == 2) {
            strQuery = "SELECT p FROM Partner p";
        }


        System.out.println("query: " + strQuery);

        //ne kreirat novu, vec koristit postojeci em
        //prm kreiranja entity manager-a
        //EntityManagerFactory emf = Persistence.createEntityManagerFactory("purgarPU");
        //EntityManager em = emf.createEntityManager();

        EntityManager em = entityManager;
        Query q = em.createQuery(strQuery);

        Collection data = q.getResultList();

        listQuery.clear();
        listQuery.addAll(data);
    }

    public void setSaveBtn(boolean var) {
        btnAcceptPart.setEnabled(var);
        btnAbort.setEnabled(var);
    }

    public void addNewPart() {
        if (!entityManager.getTransaction().isActive()) {
            entityManager.getTransaction().begin();
        } else {
            entityManager.getTransaction().rollback();
            entityManager.getTransaction().begin();
        }
        persistence.Partner part = new persistence.Partner();
        setSelected_TipPart(varKupac);
        rbKupci.setSelected(true);

        entityManager.persist(part);
        listQuery.add(part);

        int row = listQuery.size() - 1;
        tblPartneri.setRowSelectionInterval(row, row);
        tblPartneri.scrollRectToVisible(tblPartneri.getCellRect(row, 0, true));

        setSaveBtn(true);
        isNewPart = true;
    }

    public void accpetPart() {

        if (txtNaziv.getText().isEmpty() || txtAdresa.getText().isEmpty() || txtBankRac.getText().isEmpty() || txtIme.getText().isEmpty() || txtMatBr.getText().isEmpty() || txtMjesto.getText().isEmpty() || txtPostBr.getText().isEmpty() || txtPrezime.getText().isEmpty() || txtTel.getText().isEmpty()) {
            String[] btn = {"Uredu"};
            JOptionPane.showOptionDialog(null, "Niste unjeli sve podatke o poslovnom partneru!", "Poslovni partner", 0, JOptionPane.INFORMATION_MESSAGE, null, btn, 0);
            return;
        }


        entityManager.getTransaction().commit();

        entityManager.getTransaction().begin();


        if (isNewPart == true) {
            isNewPart = false;
        }
        String[] btn = {"Uredu"};
        JOptionPane.showOptionDialog(null, "Podaci o poslovnom partneru su uspješno pohranjeni!", "Poslovni partner", 0, JOptionPane.INFORMATION_MESSAGE, null, btn, 0);

        setSaveBtn(false);
    }

    public void abortPart() {
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        refreshTable();
        setSaveBtn(false);
        String[] btn = {"Uredu"};
        JOptionPane.showOptionDialog(null, "Podaci o poslovnom partneru nisu prihvaćeni!", "Poslovni partner", 0, JOptionPane.INFORMATION_MESSAGE, null, btn, 0);
    }

    public void delPart() {
        if (!entityManager.getTransaction().isActive()) {
            entityManager.getTransaction().begin();
        }
        int selRow = tblPartneri.getSelectedRow();
        int idPart = listQuery.get(selRow).getIdPartner();
        persistence.Partner part = entityManager.find(persistence.Partner.class, idPart);
        entityManager.remove(part);
        entityManager.getTransaction().commit();
        listQuery.remove(part);

        setSaveBtn(false);
        btnDelPart.setEnabled(false);
    }

    public void refreshTable() {
        int selRow = tblPartneri.getSelectedRow();

        if (!entityManager.getTransaction().isActive()) {
            //    entityManager.getTransaction().begin();
        }
        Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        listQuery.clear();
        listQuery.addAll(data);

        tblPartneri.updateUI();
        if (isNewPart != true) {
            tblPartneri.setRowSelectionInterval(selRow, selRow);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbort;
    private javax.swing.JButton btnAcceptPart;
    private javax.swing.JButton btnDelPart;
    private javax.swing.JButton btnNewPartner;
    private javax.swing.JButton btnPrintPart;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private java.util.List<persistence.Partner> listQuery;
    private javax.swing.ButtonGroup nPrikazaBtnGrp;
    private javax.persistence.Query query;
    private javax.swing.JRadioButton rbDobav;
    private javax.swing.JRadioButton rbKupci;
    private javax.swing.JRadioButton rbPartDobav;
    private javax.swing.JRadioButton rbPartKupci;
    private javax.swing.JRadioButton rbPartSvi;
    private javax.swing.JTable tblPartneri;
    private javax.swing.ButtonGroup tipPoslPartBtnGrp;
    private javax.swing.JTextField txtAdresa;
    private javax.swing.JTextField txtBankRac;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtMatBr;
    private javax.swing.JTextField txtMjesto;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtPostBr;
    private javax.swing.JTextField txtPrezime;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtTipPart;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
